// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgH3OrhdCqWdEn0UNzcP3pRSZy0xUR0Qk',
    appId: '1:102608046466:web:703c38d4453475454ba79b',
    messagingSenderId: '102608046466',
    projectId: 'fineer-fix',
    authDomain: 'fineer-fix.firebaseapp.com',
    storageBucket: 'fineer-fix.appspot.com',
    measurementId: 'G-4KFPG4BQWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9XRaGMCDXW1zLbyfAG_EoVIkfBdDUJjY',
    appId: '1:102608046466:android:76319a42f5cfe1174ba79b',
    messagingSenderId: '102608046466',
    projectId: 'fineer-fix',
    storageBucket: 'fineer-fix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxY1HQb6Jaxs_8YbVkaZzESobhJX4YKA8',
    appId: '1:102608046466:ios:628cbb55d438caad4ba79b',
    messagingSenderId: '102608046466',
    projectId: 'fineer-fix',
    storageBucket: 'fineer-fix.appspot.com',
    iosBundleId: 'com.example.fineer1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxY1HQb6Jaxs_8YbVkaZzESobhJX4YKA8',
    appId: '1:102608046466:ios:3a8687499dcd33594ba79b',
    messagingSenderId: '102608046466',
    projectId: 'fineer-fix',
    storageBucket: 'fineer-fix.appspot.com',
    iosBundleId: 'com.example.fineer1.RunnerTests',
  );
}
